; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.39"

; Modules
projects[admin_menu][version] = "3.0-rc5"

projects[ctools][version] = "1.9"

projects[devel][version] = "1.5"

projects[empty_front_page][version] = "1.0"

projects[i18n][version] = "1.13"

projects[l10n_update][version] = "2.0"

projects[module_filter][version] = "2.0"

projects[pathauto][version] = "1.2"

projects[token][version] = "1.6"

projects[transliteration][version] = "3.2"

projects[variable][version] = "2.5"

projects[views][version] = "3.11"

projects[webform][version] = "4.11"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[dst][download][type] = ""
projects[dst][download][url] = ""
projects[dst][type] = "theme"

